// Mocks generated by Mockito 5.0.16 from annotations
// in weintime/test/widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:chopper/chopper.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:weintime/auth_service.dart' as _i5;
import 'package:weintime/swagger_generated_code/wein_db.swagger.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeChopperClient_0 extends _i1.Fake implements _i2.ChopperClient {}

class _FakeType_1 extends _i1.Fake implements Type {}

class _FakeResponse_2<BodyType> extends _i1.Fake
    implements _i2.Response<BodyType> {}

class _FakeWeinDb_3 extends _i1.Fake implements _i3.WeinDb {}

/// A class which mocks [WeinDb].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeinDb extends _i1.Mock implements _i3.WeinDb {
  MockWeinDb() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChopperClient get client =>
      (super.noSuchMethod(Invocation.getter(#client),
          returnValue: _FakeChopperClient_0()) as _i2.ChopperClient);
  @override
  set client(_i2.ChopperClient? _client) =>
      super.noSuchMethod(Invocation.setter(#client, _client),
          returnValueForMissingStub: null);
  @override
  Type get definitionType =>
      (super.noSuchMethod(Invocation.getter(#definitionType),
          returnValue: _FakeType_1()) as Type);
  @override
  _i4.Future<_i2.Response<_i3.AccountGetModelWeinDbResult>> accountGet() =>
      (super.noSuchMethod(Invocation.method(#accountGet, []),
              returnValue:
                  Future<_i2.Response<_i3.AccountGetModelWeinDbResult>>.value(
                      _FakeResponse_2<_i3.AccountGetModelWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.AccountGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>> accountChangePasswordPost(
          {_i3.ChangePasswordModel? body}) =>
      (super.noSuchMethod(
              Invocation.method(#accountChangePasswordPost, [], {#body: body}),
              returnValue: Future<_i2.Response<_i3.ObjectWeinDbResult>>.value(
                  _FakeResponse_2<_i3.ObjectWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.AdminUserGetModelListWeinDbResult>>
      adminUserGet() => (super.noSuchMethod(
          Invocation.method(#adminUserGet, []),
          returnValue: Future<
                  _i2.Response<_i3.AdminUserGetModelListWeinDbResult>>.value(
              _FakeResponse_2<_i3.AdminUserGetModelListWeinDbResult>())) as _i4
          .Future<_i2.Response<_i3.AdminUserGetModelListWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.AdminUserGetModelWeinDbResult>>
      adminUserLockIdGet({int? id}) => (super.noSuchMethod(
              Invocation.method(#adminUserLockIdGet, [], {#id: id}),
              returnValue:
                  Future<_i2.Response<_i3.AdminUserGetModelWeinDbResult>>.value(
                      _FakeResponse_2<_i3.AdminUserGetModelWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.AdminUserGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.AdminUserGetModelWeinDbResult>>
      adminUserUnlockIdGet({int? id}) => (super.noSuchMethod(
              Invocation.method(#adminUserUnlockIdGet, [], {#id: id}),
              returnValue:
                  Future<_i2.Response<_i3.AdminUserGetModelWeinDbResult>>.value(
                      _FakeResponse_2<_i3.AdminUserGetModelWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.AdminUserGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.AdminUserGetModelWeinDbResult>>
      adminUserDeleteIdDelete({int? id}) => (super.noSuchMethod(
              Invocation.method(#adminUserDeleteIdDelete, [], {#id: id}),
              returnValue:
                  Future<_i2.Response<_i3.AdminUserGetModelWeinDbResult>>.value(
                      _FakeResponse_2<_i3.AdminUserGetModelWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.AdminUserGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>> adminUserActivateIdGet(
          {int? id}) =>
      (super.noSuchMethod(
              Invocation.method(#adminUserActivateIdGet, [], {#id: id}),
              returnValue: Future<_i2.Response<_i3.ObjectWeinDbResult>>.value(
                  _FakeResponse_2<_i3.ObjectWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.AdminUserGetModelWeinDbResult>>
      adminUserToggleAdminIdGet({int? id}) => (super.noSuchMethod(
              Invocation.method(#adminUserToggleAdminIdGet, [], {#id: id}),
              returnValue:
                  Future<_i2.Response<_i3.AdminUserGetModelWeinDbResult>>.value(
                      _FakeResponse_2<_i3.AdminUserGetModelWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.AdminUserGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.GrapeVarietyGetModelListWeinDbResult>>
      grapeVarietyGet() => (super.noSuchMethod(
              Invocation.method(#grapeVarietyGet, []),
              returnValue: Future<
                      _i2.Response<
                          _i3.GrapeVarietyGetModelListWeinDbResult>>.value(
                  _FakeResponse_2<_i3.GrapeVarietyGetModelListWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.GrapeVarietyGetModelListWeinDbResult>>);
  @override
  _i4.Future<
      _i2.Response<_i3.GrapeVarietyGetModelWeinDbResult>> grapeVarietyPost(
          {_i3.GrapeVarietyCreateModel? body}) =>
      (super.noSuchMethod(
          Invocation.method(#grapeVarietyPost, [], {#body: body}),
          returnValue:
              Future<_i2.Response<_i3.GrapeVarietyGetModelWeinDbResult>>.value(
                  _FakeResponse_2<_i3.GrapeVarietyGetModelWeinDbResult>())) as _i4
          .Future<_i2.Response<_i3.GrapeVarietyGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>> grapeVarietyPut(
          {_i3.GrapeVarietyEditModel? body}) =>
      (super.noSuchMethod(
              Invocation.method(#grapeVarietyPut, [], {#body: body}),
              returnValue: Future<_i2.Response<_i3.ObjectWeinDbResult>>.value(
                  _FakeResponse_2<_i3.ObjectWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.GrapeVarietyGetModelWeinDbResult>>
      grapeVarietyIdGet({int? id}) => (super.noSuchMethod(
              Invocation.method(#grapeVarietyIdGet, [], {#id: id}),
              returnValue: Future<
                      _i2.Response<_i3.GrapeVarietyGetModelWeinDbResult>>.value(
                  _FakeResponse_2<_i3.GrapeVarietyGetModelWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.GrapeVarietyGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>> grapeVarietyIdDelete(
          {int? id}) =>
      (super.noSuchMethod(
              Invocation.method(#grapeVarietyIdDelete, [], {#id: id}),
              returnValue: Future<_i2.Response<_i3.ObjectWeinDbResult>>.value(
                  _FakeResponse_2<_i3.ObjectWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.RegionGetModelListWeinDbResult>> regionGet() =>
      (super.noSuchMethod(Invocation.method(#regionGet, []),
          returnValue:
              Future<_i2.Response<_i3.RegionGetModelListWeinDbResult>>.value(
                  _FakeResponse_2<_i3.RegionGetModelListWeinDbResult>())) as _i4
          .Future<_i2.Response<_i3.RegionGetModelListWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.RegionGetModelWeinDbResult>> regionPost(
          {_i3.RegionCreateModel? body}) =>
      (super.noSuchMethod(Invocation.method(#regionPost, [], {#body: body}),
              returnValue:
                  Future<_i2.Response<_i3.RegionGetModelWeinDbResult>>.value(
                      _FakeResponse_2<_i3.RegionGetModelWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.RegionGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>> regionPut(
          {_i3.RegionEditModel? body}) =>
      (super.noSuchMethod(Invocation.method(#regionPut, [], {#body: body}),
              returnValue: Future<_i2.Response<_i3.ObjectWeinDbResult>>.value(
                  _FakeResponse_2<_i3.ObjectWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.RegionGetModelWeinDbResult>> regionIdGet(
          {int? id}) =>
      (super.noSuchMethod(Invocation.method(#regionIdGet, [], {#id: id}),
              returnValue:
                  Future<_i2.Response<_i3.RegionGetModelWeinDbResult>>.value(
                      _FakeResponse_2<_i3.RegionGetModelWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.RegionGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>> regionIdDelete({int? id}) =>
      (super.noSuchMethod(Invocation.method(#regionIdDelete, [], {#id: id}),
              returnValue: Future<_i2.Response<_i3.ObjectWeinDbResult>>.value(
                  _FakeResponse_2<_i3.ObjectWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.UserGetModelWeinDbResult>> registerPost(
          {_i3.UserRegisterModel? body}) =>
      (super.noSuchMethod(Invocation.method(#registerPost, [], {#body: body}),
          returnValue: Future<_i2.Response<_i3.UserGetModelWeinDbResult>>.value(
              _FakeResponse_2<_i3.UserGetModelWeinDbResult>())) as _i4
          .Future<_i2.Response<_i3.UserGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.ApiLoginResult>> tokenPost(
          {String? username,
          String? password,
          String? grantType,
          String? refreshToken}) =>
      (super.noSuchMethod(
              Invocation.method(#tokenPost, [], {
                #username: username,
                #password: password,
                #grantType: grantType,
                #refreshToken: refreshToken
              }),
              returnValue: Future<_i2.Response<_i3.ApiLoginResult>>.value(
                  _FakeResponse_2<_i3.ApiLoginResult>()))
          as _i4.Future<_i2.Response<_i3.ApiLoginResult>>);
  @override
  _i4.Future<_i2.Response<_i3.VendorGetModelListWeinDbResult>> vendorGet() =>
      (super.noSuchMethod(Invocation.method(#vendorGet, []),
          returnValue:
              Future<_i2.Response<_i3.VendorGetModelListWeinDbResult>>.value(
                  _FakeResponse_2<_i3.VendorGetModelListWeinDbResult>())) as _i4
          .Future<_i2.Response<_i3.VendorGetModelListWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.VendorGetModelWeinDbResult>> vendorPost(
          {_i3.VendorCreateModel? body}) =>
      (super.noSuchMethod(Invocation.method(#vendorPost, [], {#body: body}),
              returnValue:
                  Future<_i2.Response<_i3.VendorGetModelWeinDbResult>>.value(
                      _FakeResponse_2<_i3.VendorGetModelWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.VendorGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>> vendorPut(
          {_i3.VendorEditModel? body}) =>
      (super.noSuchMethod(Invocation.method(#vendorPut, [], {#body: body}),
              returnValue: Future<_i2.Response<_i3.ObjectWeinDbResult>>.value(
                  _FakeResponse_2<_i3.ObjectWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.VendorGetModelWeinDbResult>> vendorIdGet(
          {int? id}) =>
      (super.noSuchMethod(Invocation.method(#vendorIdGet, [], {#id: id}),
              returnValue:
                  Future<_i2.Response<_i3.VendorGetModelWeinDbResult>>.value(
                      _FakeResponse_2<_i3.VendorGetModelWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.VendorGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>> vendorIdDelete({int? id}) =>
      (super.noSuchMethod(Invocation.method(#vendorIdDelete, [], {#id: id}),
              returnValue: Future<_i2.Response<_i3.ObjectWeinDbResult>>.value(
                  _FakeResponse_2<_i3.ObjectWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.WineListWeinDbResult>> wineGet() =>
      (super.noSuchMethod(Invocation.method(#wineGet, []),
              returnValue: Future<_i2.Response<_i3.WineListWeinDbResult>>.value(
                  _FakeResponse_2<_i3.WineListWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.WineListWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.WineTypeGetModelListWeinDbResult>>
      wineTypeGet() => (super.noSuchMethod(Invocation.method(#wineTypeGet, []),
              returnValue: Future<
                      _i2.Response<_i3.WineTypeGetModelListWeinDbResult>>.value(
                  _FakeResponse_2<_i3.WineTypeGetModelListWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.WineTypeGetModelListWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.WineTypeGetModelWeinDbResult>> wineTypePost(
          {_i3.WineTypeCreateModel? body}) =>
      (super.noSuchMethod(Invocation.method(#wineTypePost, [], {#body: body}),
              returnValue:
                  Future<_i2.Response<_i3.WineTypeGetModelWeinDbResult>>.value(
                      _FakeResponse_2<_i3.WineTypeGetModelWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.WineTypeGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>> wineTypePut(
          {_i3.WineTypeEditModel? body}) =>
      (super.noSuchMethod(Invocation.method(#wineTypePut, [], {#body: body}),
              returnValue: Future<_i2.Response<_i3.ObjectWeinDbResult>>.value(
                  _FakeResponse_2<_i3.ObjectWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.WineTypeGetModelWeinDbResult>> wineTypeIdGet(
          {int? id}) =>
      (super.noSuchMethod(Invocation.method(#wineTypeIdGet, [], {#id: id}),
              returnValue:
                  Future<_i2.Response<_i3.WineTypeGetModelWeinDbResult>>.value(
                      _FakeResponse_2<_i3.WineTypeGetModelWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.WineTypeGetModelWeinDbResult>>);
  @override
  _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>> wineTypeIdDelete(
          {int? id}) =>
      (super.noSuchMethod(Invocation.method(#wineTypeIdDelete, [], {#id: id}),
              returnValue: Future<_i2.Response<_i3.ObjectWeinDbResult>>.value(
                  _FakeResponse_2<_i3.ObjectWeinDbResult>()))
          as _i4.Future<_i2.Response<_i3.ObjectWeinDbResult>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.WeinDb get weinDb => (super.noSuchMethod(Invocation.getter(#weinDb),
      returnValue: _FakeWeinDb_3()) as _i3.WeinDb);
  @override
  set weinDb(_i3.WeinDb? _weinDb) =>
      super.noSuchMethod(Invocation.setter(#weinDb, _weinDb),
          returnValueForMissingStub: null);
  @override
  _i4.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(Invocation.method(#isLoggedIn, []),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<bool> login(String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#login, [username, password]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(Invocation.method(#logout, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}
